# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fast-Api App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DB_NAME: test_db
        DB_NAME_TESTING: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_SERVER: localhost:3306
        PASSWORD_SECRET: ${{ secrets.HashPassword }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sorting imports and linting with isort and black
      run: |
        cd backend/src && isort . --profile black
    - name: Test with pytest
      run: |
        pytest backend/src